### ISSUE TITLE
support aeson-2.1?

### ISSUE THREAD

**Issue by juhp** [phadej/aeson-compat#55]
I don't personally use this library, but noticed in Fedora that it fails to build with aeson-2.1
(currently there is an upperbound for that)

```
src/Data/Aeson/Compat.hs:174:20: error:
    Ambiguous occurrence ‘AesonException’
    It could refer to
       either ‘Data.Aeson.AesonException’,
              imported from ‘Data.Aeson’ at src/Data/Aeson/Compat.hs:(100,1)-(111,3)
           or ‘Data.Aeson.Compat.AesonException’,
              defined at src/Data/Aeson/Compat.hs:171:1
    |
174 | instance Exception AesonException
    |                    ^^^^^^^^^^^^^^

src/Data/Aeson/Compat.hs:177:37: error:
    Ambiguous occurrence ‘AesonException’
    It could refer to
       either ‘Data.Aeson.AesonException’,
              imported from ‘Data.Aeson’ at src/Data/Aeson/Compat.hs:(100,1)-(111,3)
           or ‘Data.Aeson.Compat.AesonException’,
              defined at src/Data/Aeson/Compat.hs:171:26
    |
177 | eitherAesonExc (Left err) = throwM (AesonException err)
    |                                     ^^^^^^^^^^^^^^

```

**Comment by phadej** [comment]
Do you use `allow-newer`? Which version is this?

**Comment by juhp** [comment]
Yes I am aware there is an upperbound on aeson.

I patched 0.3.10 to get the above result.
We could probably drop aeson-compat from Fedora.

**Comment by phadej** [comment]
> We could probably drop aeson-compat from Fedora.

Do it. I'm not updating `aeson-compat` anymore, it has served it's purpose.
